require("prototypes.technology.radar")
require("prototypes.item.surveillance")
require("prototypes.recipe.surveillance")
require("prototypes.entity.blueprint-radar")
require("prototypes.entity.surveillance")
